### ISSUE TITLE
Possible to get metadata about feed?

### ISSUE THREAD

**Issue by ryanfiller** [mottox2/gatsby-source-rss-feed#11]
I notice in the source that the plugin only returns data about each feed `<item>`.
```const feed = await parser.parseURL(url)
  feed.items.forEach(item => ...)
```

`rss-parser` [seems like its supports custom feed options](https://github.com/rbren/rss-parser#custom-fields). Any chance we can somehow use that to grab the `<title>`, `<description>`, or maybe even other from the feed url?

**Comment by ryanfiller** [comment]
I opened a PR for this [here](https://github.com/mottox2/gatsby-source-rss-feed/pull/12)

**Comment by mottox2** [comment]
Thanks for your PR.
Published in gatsby-source-rss-feed@1.2.0.
